name: End-to-end
on: push
jobs:
  cypress-run-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        id: cypress 
        with:
          command: npm run teste:GETapi

      - name: Enviar mensagem para g-chat
        if: always() # Este passo sempre será executado, independentemente do status anterior
        run: |
          if [ "${{ steps.cypress.outcome }}" == "success" ]; then
            status="Todos os testes passaram com sucesso!"
          else
            status="Alguns testes falharam."
          fi
          curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"${status}\"}" "https://chat.googleapis.com/v1/spaces/AAAATzKXhvA/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=hKCSdPs13r28hOwKxJsTjx1c-ODv1qReIoe2VsBuR54"
