name: PageSpeedCase
on: push
jobs:
  cypress-run-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        id: cypress 
        with:
          command: npm run teste:GETapi

      - name: Enviar resultado G-chat
        if: always()
        env:
          WEBHOOK_URL: "https://chat.googleapis.com/v1/spaces/AAAATzKXhvA/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=hKCSdPs13r28hOwKxJsTjx1c-ODv1qReIoe2VsBuR54"
        run: |
          if [ "${{ steps.cypress.outcome }}" == "success" ]; then
            status="Todos os testes passaram com sucesso!"
            color="#28a745" # Verde
            imageUrl="https://w7.pngwing.com/pngs/485/477/png-transparent-check-mark-computer-icons-green-check-circle-angle-text-logo.png"
          else
            status="Alguns testes falharam."
            color="#d73a49" # Vermelho
            imageUrl="https://th.bing.com/th/id/R.301c1124d94ad1b5bf4c176b6d6c888a?rik=cz3KZVHK414iIA&riu=http%3a%2f%2fclipart-library.com%2fimages_k%2fred-check-mark-transparent-background%2fred-check-mark-transparent-background-22.jpg&ehk=Jlgk67LB24hq77es%2fmcEaPNnzNGEwF8naLT%2f1ywaQAM%3d&risl=&pid=ImgRaw&r=0"
          fi

          json_payload=$(echo '{
            "cards": [
              {
                "header": {
                  "title": "Resultado da Pipeline: PageSpeedCase",
                  "subtitle": "'"${status}"'",
                  "imageUrl": "'"${imageUrl}"'",
                  "imageStyle": "AVATAR"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "A execução da pipeline <b>PageSpeedCase</b> foi concluída."
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Status",
                          "content": "'"${status}"'",
                          "contentMultiline": "false",
                          "icon": "DESCRIPTION",
                          "button": {
                            "textButton": {
                              "text": "Ver Detalhes",
                              "onClick": {
                                "openLink": {
                                  "url": "https://github.com/Rafael-Sampaio-QA/PageSpeed"
                                }
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }')

          curl -X POST -H "Content-Type: application/json" -d "$json_payload" "$WEBHOOK_URL"
