name: PageSpeedCase
on: push
jobs:
  cypress-run-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        id: cypress 
        with:
          command: npm run teste:GETapi

      - name: Enviar Mensagem G-Chat
        if: always()
        env:
          WEBHOOK_URL: "https://chat.googleapis.com/v1/spaces/AAAATzKXhvA/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=hKCSdPs13r28hOwKxJsTjx1c-ODv1qReIoe2VsBuR54"
        run: |
          if [ "${{ steps.cypress.outcome }}" == "success" ]; then
            status="Todos os testes passaram com sucesso!"
            
          else
            status="Alguns testes falharam."
            
          fi

          json_payload=$(echo '{
            "cards": [
              {
                "header": {
                  "title": "Resultado da Pipeline: PageSpeedCase",
                  "subtitle": "'"${status}"'",
                  "imageUrl": "https://www.finsmes.com/wp-content/uploads/2020/12/cypress.jpg",
                  "imageStyle": "AVATAR"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "A execução da pipeline <b>PageSpeedCase</b> foi concluída."
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Status",
                          "content": "'"${status}"'",
                          "contentMultiline": "false",
                          "icon": "DESCRIPTION",
                          "button": {
                            "textButton": {
                              "text": "Ver Detalhes",
                              "onClick": {
                                "openLink": {
                                  "url": ""
                                }
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }')

          curl -X POST -H "Content-Type: application/json" -d "$json_payload" "$WEBHOOK_URL"
